// File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

package com.openai.services.blocking

import com.google.errorprone.annotations.MustBeClosed
import com.openai.core.ClientOptions
import com.openai.core.RequestOptions
import com.openai.core.http.HttpResponseFor
import com.openai.models.contentprovenancechecks.ContentProvenanceCheck
import com.openai.models.contentprovenancechecks.ContentProvenanceCheckCreateParams
import java.util.function.Consumer

interface ContentProvenanceCheckService {

    /**
     * Returns a view of this service that provides access to raw HTTP responses for each method.
     */
    fun withRawResponse(): WithRawResponse

    /**
     * Returns a view of this service with the given option modifications applied.
     *
     * The original service is not modified.
     */
    fun withOptions(modifier: Consumer<ClientOptions.Builder>): ContentProvenanceCheckService

    /**
     * Check whether an image or audio file contains known OpenAI provenance signals.
     * [Learn more about content provenance](/api/docs/guides/content-provenance).
     *
     * If `not_detected`, it means the tool did not find supported signals in the uploaded file. The
     * content could still have been generated by OpenAI if the metadata was stripped or has
     * evidence of tampering, the watermark was degraded, it comes from a legacy generation model,
     * or it was created before provenance signals were available. Content could also still be
     * AI-generated by another company's model, which the tool currently does not detect.
     */
    fun create(params: ContentProvenanceCheckCreateParams): ContentProvenanceCheck =
        create(params, RequestOptions.none())

    /** @see create */
    fun create(
        params: ContentProvenanceCheckCreateParams,
        requestOptions: RequestOptions = RequestOptions.none(),
    ): ContentProvenanceCheck

    /**
     * A view of [ContentProvenanceCheckService] that provides access to raw HTTP responses for each
     * method.
     */
    interface WithRawResponse {

        /**
         * Returns a view of this service with the given option modifications applied.
         *
         * The original service is not modified.
         */
        fun withOptions(
            modifier: Consumer<ClientOptions.Builder>
        ): ContentProvenanceCheckService.WithRawResponse

        /**
         * Returns a raw HTTP response for `post /content_provenance_checks`, but is otherwise the
         * same as [ContentProvenanceCheckService.create].
         */
        @MustBeClosed
        fun create(
            params: ContentProvenanceCheckCreateParams
        ): HttpResponseFor<ContentProvenanceCheck> = create(params, RequestOptions.none())

        /** @see create */
        @MustBeClosed
        fun create(
            params: ContentProvenanceCheckCreateParams,
            requestOptions: RequestOptions = RequestOptions.none(),
        ): HttpResponseFor<ContentProvenanceCheck>
    }
}
