// File generated from our OpenAPI spec by Stainless.

package com.openai.models.beta.responses

import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import com.openai.core.Enum
import com.openai.core.ExcludeMissing
import com.openai.core.JsonField
import com.openai.core.JsonMissing
import com.openai.core.JsonValue
import com.openai.core.checkRequired
import com.openai.errors.OpenAIInvalidDataException
import java.util.Collections
import java.util.Objects
import java.util.Optional
import kotlin.jvm.optionals.getOrNull

/** The output of a custom tool call from your code, being sent back to the model. */
class BetaResponseCustomToolCallOutputItem
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val callId: JsonField<String>,
    private val output: JsonField<BetaResponseCustomToolCallOutput.Output>,
    private val type: JsonValue,
    private val id: JsonField<String>,
    private val agent: JsonField<BetaResponseCustomToolCallOutput.Agent>,
    private val caller: JsonField<BetaResponseCustomToolCallOutput.Caller>,
    private val status: JsonField<Status>,
    private val createdBy: JsonField<String>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("call_id") @ExcludeMissing callId: JsonField<String> = JsonMissing.of(),
        @JsonProperty("output")
        @ExcludeMissing
        output: JsonField<BetaResponseCustomToolCallOutput.Output> = JsonMissing.of(),
        @JsonProperty("type") @ExcludeMissing type: JsonValue = JsonMissing.of(),
        @JsonProperty("id") @ExcludeMissing id: JsonField<String> = JsonMissing.of(),
        @JsonProperty("agent")
        @ExcludeMissing
        agent: JsonField<BetaResponseCustomToolCallOutput.Agent> = JsonMissing.of(),
        @JsonProperty("caller")
        @ExcludeMissing
        caller: JsonField<BetaResponseCustomToolCallOutput.Caller> = JsonMissing.of(),
        @JsonProperty("status") @ExcludeMissing status: JsonField<Status> = JsonMissing.of(),
        @JsonProperty("created_by") @ExcludeMissing createdBy: JsonField<String> = JsonMissing.of(),
    ) : this(callId, output, type, id, agent, caller, status, createdBy, mutableMapOf())

    fun toBetaResponseCustomToolCallOutput(): BetaResponseCustomToolCallOutput =
        BetaResponseCustomToolCallOutput.builder()
            .callId(callId)
            .output(output)
            .type(type)
            .id(id)
            .agent(agent)
            .caller(caller)
            .build()

    /**
     * The call ID, used to map this custom tool call output to a custom tool call.
     *
     * @throws OpenAIInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun callId(): String = callId.getRequired("call_id")

    /**
     * The output from the custom tool call generated by your code. Can be a string or an list of
     * output content.
     *
     * @throws OpenAIInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun output(): BetaResponseCustomToolCallOutput.Output = output.getRequired("output")

    /**
     * The type of the custom tool call output. Always `custom_tool_call_output`.
     *
     * Expected to always return the following:
     * ```java
     * JsonValue.from("custom_tool_call_output")
     * ```
     *
     * However, this method can be useful for debugging and logging (e.g. if the server responded
     * with an unexpected value).
     */
    @JsonProperty("type") @ExcludeMissing fun _type(): JsonValue = type

    /**
     * The unique ID of the custom tool call output in the OpenAI platform.
     *
     * @throws OpenAIInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun id(): Optional<String> = id.getOptional("id")

    /**
     * The agent that produced this item.
     *
     * @throws OpenAIInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun agent(): Optional<BetaResponseCustomToolCallOutput.Agent> = agent.getOptional("agent")

    /**
     * The execution context that produced this tool call.
     *
     * @throws OpenAIInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun caller(): Optional<BetaResponseCustomToolCallOutput.Caller> = caller.getOptional("caller")

    /**
     * The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when
     * items are returned via API.
     *
     * @throws OpenAIInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun status(): Status = status.getRequired("status")

    /**
     * The identifier of the actor that created the item.
     *
     * @throws OpenAIInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun createdBy(): Optional<String> = createdBy.getOptional("created_by")

    /**
     * Returns the raw JSON value of [callId].
     *
     * Unlike [callId], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("call_id") @ExcludeMissing fun _callId(): JsonField<String> = callId

    /**
     * Returns the raw JSON value of [output].
     *
     * Unlike [output], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("output")
    @ExcludeMissing
    fun _output(): JsonField<BetaResponseCustomToolCallOutput.Output> = output

    /**
     * Returns the raw JSON value of [id].
     *
     * Unlike [id], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("id") @ExcludeMissing fun _id(): JsonField<String> = id

    /**
     * Returns the raw JSON value of [agent].
     *
     * Unlike [agent], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("agent")
    @ExcludeMissing
    fun _agent(): JsonField<BetaResponseCustomToolCallOutput.Agent> = agent

    /**
     * Returns the raw JSON value of [caller].
     *
     * Unlike [caller], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("caller")
    @ExcludeMissing
    fun _caller(): JsonField<BetaResponseCustomToolCallOutput.Caller> = caller

    /**
     * Returns the raw JSON value of [status].
     *
     * Unlike [status], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("status") @ExcludeMissing fun _status(): JsonField<Status> = status

    /**
     * Returns the raw JSON value of [createdBy].
     *
     * Unlike [createdBy], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("created_by") @ExcludeMissing fun _createdBy(): JsonField<String> = createdBy

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of
         * [BetaResponseCustomToolCallOutputItem].
         *
         * The following fields are required:
         * ```java
         * .callId()
         * .output()
         * .status()
         * ```
         */
        @JvmStatic fun builder() = Builder()
    }

    /** A builder for [BetaResponseCustomToolCallOutputItem]. */
    class Builder internal constructor() {

        private var callId: JsonField<String>? = null
        private var output: JsonField<BetaResponseCustomToolCallOutput.Output>? = null
        private var type: JsonValue = JsonValue.from("custom_tool_call_output")
        private var id: JsonField<String> = JsonMissing.of()
        private var agent: JsonField<BetaResponseCustomToolCallOutput.Agent> = JsonMissing.of()
        private var caller: JsonField<BetaResponseCustomToolCallOutput.Caller> = JsonMissing.of()
        private var status: JsonField<Status>? = null
        private var createdBy: JsonField<String> = JsonMissing.of()
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        @JvmSynthetic
        internal fun from(
            betaResponseCustomToolCallOutputItem: BetaResponseCustomToolCallOutputItem
        ) = apply {
            callId = betaResponseCustomToolCallOutputItem.callId
            output = betaResponseCustomToolCallOutputItem.output
            type = betaResponseCustomToolCallOutputItem.type
            id = betaResponseCustomToolCallOutputItem.id
            agent = betaResponseCustomToolCallOutputItem.agent
            caller = betaResponseCustomToolCallOutputItem.caller
            status = betaResponseCustomToolCallOutputItem.status
            createdBy = betaResponseCustomToolCallOutputItem.createdBy
            additionalProperties =
                betaResponseCustomToolCallOutputItem.additionalProperties.toMutableMap()
        }

        /** The call ID, used to map this custom tool call output to a custom tool call. */
        fun callId(callId: String) = callId(JsonField.of(callId))

        /**
         * Sets [Builder.callId] to an arbitrary JSON value.
         *
         * You should usually call [Builder.callId] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun callId(callId: JsonField<String>) = apply { this.callId = callId }

        /**
         * The output from the custom tool call generated by your code. Can be a string or an list
         * of output content.
         */
        fun output(output: BetaResponseCustomToolCallOutput.Output) = output(JsonField.of(output))

        /**
         * Sets [Builder.output] to an arbitrary JSON value.
         *
         * You should usually call [Builder.output] with a well-typed
         * [BetaResponseCustomToolCallOutput.Output] value instead. This method is primarily for
         * setting the field to an undocumented or not yet supported value.
         */
        fun output(output: JsonField<BetaResponseCustomToolCallOutput.Output>) = apply {
            this.output = output
        }

        /**
         * Alias for calling [output] with
         * `BetaResponseCustomToolCallOutput.Output.ofString(string)`.
         */
        fun output(string: String) =
            output(BetaResponseCustomToolCallOutput.Output.ofString(string))

        /**
         * Alias for calling [output] with
         * `BetaResponseCustomToolCallOutput.Output.ofContentList(contentList)`.
         */
        fun outputOfContentList(
            contentList:
                List<BetaResponseCustomToolCallOutput.Output.BetaFunctionAndCustomToolCallOutput>
        ) = output(BetaResponseCustomToolCallOutput.Output.ofContentList(contentList))

        /**
         * Sets the field to an arbitrary JSON value.
         *
         * It is usually unnecessary to call this method because the field defaults to the
         * following:
         * ```java
         * JsonValue.from("custom_tool_call_output")
         * ```
         *
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun type(type: JsonValue) = apply { this.type = type }

        /** The unique ID of the custom tool call output in the OpenAI platform. */
        fun id(id: String) = id(JsonField.of(id))

        /**
         * Sets [Builder.id] to an arbitrary JSON value.
         *
         * You should usually call [Builder.id] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun id(id: JsonField<String>) = apply { this.id = id }

        /** The agent that produced this item. */
        fun agent(agent: BetaResponseCustomToolCallOutput.Agent?) =
            agent(JsonField.ofNullable(agent))

        /** Alias for calling [Builder.agent] with `agent.orElse(null)`. */
        fun agent(agent: Optional<BetaResponseCustomToolCallOutput.Agent>) =
            agent(agent.getOrNull())

        /**
         * Sets [Builder.agent] to an arbitrary JSON value.
         *
         * You should usually call [Builder.agent] with a well-typed
         * [BetaResponseCustomToolCallOutput.Agent] value instead. This method is primarily for
         * setting the field to an undocumented or not yet supported value.
         */
        fun agent(agent: JsonField<BetaResponseCustomToolCallOutput.Agent>) = apply {
            this.agent = agent
        }

        /** The execution context that produced this tool call. */
        fun caller(caller: BetaResponseCustomToolCallOutput.Caller?) =
            caller(JsonField.ofNullable(caller))

        /** Alias for calling [Builder.caller] with `caller.orElse(null)`. */
        fun caller(caller: Optional<BetaResponseCustomToolCallOutput.Caller>) =
            caller(caller.getOrNull())

        /**
         * Sets [Builder.caller] to an arbitrary JSON value.
         *
         * You should usually call [Builder.caller] with a well-typed
         * [BetaResponseCustomToolCallOutput.Caller] value instead. This method is primarily for
         * setting the field to an undocumented or not yet supported value.
         */
        fun caller(caller: JsonField<BetaResponseCustomToolCallOutput.Caller>) = apply {
            this.caller = caller
        }

        /** Alias for calling [caller] with `BetaResponseCustomToolCallOutput.Caller.ofDirect()`. */
        fun callerDirect() = caller(BetaResponseCustomToolCallOutput.Caller.ofDirect())

        /**
         * Alias for calling [caller] with
         * `BetaResponseCustomToolCallOutput.Caller.ofProgram(program)`.
         */
        fun caller(program: BetaResponseCustomToolCallOutput.Caller.Program) =
            caller(BetaResponseCustomToolCallOutput.Caller.ofProgram(program))

        /**
         * Alias for calling [caller] with the following:
         * ```java
         * BetaResponseCustomToolCallOutput.Caller.Program.builder()
         *     .callerId(callerId)
         *     .build()
         * ```
         */
        fun programCaller(callerId: String) =
            caller(
                BetaResponseCustomToolCallOutput.Caller.Program.builder().callerId(callerId).build()
            )

        /**
         * The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated
         * when items are returned via API.
         */
        fun status(status: Status) = status(JsonField.of(status))

        /**
         * Sets [Builder.status] to an arbitrary JSON value.
         *
         * You should usually call [Builder.status] with a well-typed [Status] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun status(status: JsonField<Status>) = apply { this.status = status }

        /** The identifier of the actor that created the item. */
        fun createdBy(createdBy: String) = createdBy(JsonField.of(createdBy))

        /**
         * Sets [Builder.createdBy] to an arbitrary JSON value.
         *
         * You should usually call [Builder.createdBy] with a well-typed [String] value instead.
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun createdBy(createdBy: JsonField<String>) = apply { this.createdBy = createdBy }

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [BetaResponseCustomToolCallOutputItem].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```java
         * .callId()
         * .output()
         * .status()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): BetaResponseCustomToolCallOutputItem =
            BetaResponseCustomToolCallOutputItem(
                checkRequired("callId", callId),
                checkRequired("output", output),
                type,
                id,
                agent,
                caller,
                checkRequired("status", status),
                createdBy,
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws OpenAIInvalidDataException if any value type in this object doesn't match its
     *   expected type.
     */
    fun validate(): BetaResponseCustomToolCallOutputItem = apply {
        if (validated) {
            return@apply
        }

        callId()
        output().validate()
        _type().let {
            if (it != JsonValue.from("custom_tool_call_output")) {
                throw OpenAIInvalidDataException("'type' is invalid, received $it")
            }
        }
        id()
        agent().ifPresent { it.validate() }
        caller().ifPresent { it.validate() }
        status().validate()
        createdBy()
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: OpenAIInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    @JvmSynthetic
    internal fun validity(): Int =
        (if (callId.asKnown().isPresent) 1 else 0) +
            (output.asKnown().getOrNull()?.validity() ?: 0) +
            type.let { if (it == JsonValue.from("custom_tool_call_output")) 1 else 0 } +
            (if (id.asKnown().isPresent) 1 else 0) +
            (agent.asKnown().getOrNull()?.validity() ?: 0) +
            (caller.asKnown().getOrNull()?.validity() ?: 0) +
            (status.asKnown().getOrNull()?.validity() ?: 0) +
            (if (createdBy.asKnown().isPresent) 1 else 0)

    /**
     * The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when
     * items are returned via API.
     */
    class Status @JsonCreator private constructor(private val value: JsonField<String>) : Enum {

        /**
         * Returns this class instance's raw value.
         *
         * This is usually only useful if this instance was deserialized from data that doesn't
         * match any known member, and you want to know that value. For example, if the SDK is on an
         * older version than the API, then the API may respond with new members that the SDK is
         * unaware of.
         */
        @com.fasterxml.jackson.annotation.JsonValue fun _value(): JsonField<String> = value

        companion object {

            @JvmField val IN_PROGRESS = of("in_progress")

            @JvmField val COMPLETED = of("completed")

            @JvmField val INCOMPLETE = of("incomplete")

            @JvmStatic fun of(value: String) = Status(JsonField.of(value))
        }

        /** An enum containing [Status]'s known values. */
        enum class Known {
            IN_PROGRESS,
            COMPLETED,
            INCOMPLETE,
        }

        /**
         * An enum containing [Status]'s known values, as well as an [_UNKNOWN] member.
         *
         * An instance of [Status] can contain an unknown value in a couple of cases:
         * - It was deserialized from data that doesn't match any known member. For example, if the
         *   SDK is on an older version than the API, then the API may respond with new members that
         *   the SDK is unaware of.
         * - It was constructed with an arbitrary value using the [of] method.
         */
        enum class Value {
            IN_PROGRESS,
            COMPLETED,
            INCOMPLETE,
            /** An enum member indicating that [Status] was instantiated with an unknown value. */
            _UNKNOWN,
        }

        /**
         * Returns an enum member corresponding to this class instance's value, or [Value._UNKNOWN]
         * if the class was instantiated with an unknown value.
         *
         * Use the [known] method instead if you're certain the value is always known or if you want
         * to throw for the unknown case.
         */
        fun value(): Value =
            when (this) {
                IN_PROGRESS -> Value.IN_PROGRESS
                COMPLETED -> Value.COMPLETED
                INCOMPLETE -> Value.INCOMPLETE
                else -> Value._UNKNOWN
            }

        /**
         * Returns an enum member corresponding to this class instance's value.
         *
         * Use the [value] method instead if you're uncertain the value is always known and don't
         * want to throw for the unknown case.
         *
         * @throws OpenAIInvalidDataException if this class instance's value is a not a known
         *   member.
         */
        fun known(): Known =
            when (this) {
                IN_PROGRESS -> Known.IN_PROGRESS
                COMPLETED -> Known.COMPLETED
                INCOMPLETE -> Known.INCOMPLETE
                else -> throw OpenAIInvalidDataException("Unknown Status: $value")
            }

        /**
         * Returns this class instance's primitive wire representation.
         *
         * This differs from the [toString] method because that method is primarily for debugging
         * and generally doesn't throw.
         *
         * @throws OpenAIInvalidDataException if this class instance's value does not have the
         *   expected primitive type.
         */
        fun asString(): String =
            _value().asString().orElseThrow { OpenAIInvalidDataException("Value is not a String") }

        private var validated: Boolean = false

        /**
         * Validates that the types of all values in this object match their expected types
         * recursively.
         *
         * This method is _not_ forwards compatible with new types from the API for existing fields.
         *
         * @throws OpenAIInvalidDataException if any value type in this object doesn't match its
         *   expected type.
         */
        fun validate(): Status = apply {
            if (validated) {
                return@apply
            }

            known()
            validated = true
        }

        fun isValid(): Boolean =
            try {
                validate()
                true
            } catch (e: OpenAIInvalidDataException) {
                false
            }

        /**
         * Returns a score indicating how many valid values are contained in this object
         * recursively.
         *
         * Used for best match union deserialization.
         */
        @JvmSynthetic internal fun validity(): Int = if (value() == Value._UNKNOWN) 0 else 1

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return other is Status && value == other.value
        }

        override fun hashCode() = value.hashCode()

        override fun toString() = value.toString()
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is BetaResponseCustomToolCallOutputItem &&
            callId == other.callId &&
            output == other.output &&
            type == other.type &&
            id == other.id &&
            agent == other.agent &&
            caller == other.caller &&
            status == other.status &&
            createdBy == other.createdBy &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy {
        Objects.hash(
            callId,
            output,
            type,
            id,
            agent,
            caller,
            status,
            createdBy,
            additionalProperties,
        )
    }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "BetaResponseCustomToolCallOutputItem{callId=$callId, output=$output, type=$type, id=$id, agent=$agent, caller=$caller, status=$status, createdBy=$createdBy, additionalProperties=$additionalProperties}"
}
