#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Testing build logic"
./scripts/gradle :buildSrc:test "$@"

echo "==> Building classes"
./scripts/gradle build testClasses verifyVersionSupportPolicy "$@" -x test
