#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Running gradlew formatKotlin"
./scripts/gradle formatKotlin

if command -v palantir-java-format &> /dev/null; then
    echo "==> Running palantir-java-format"
    ./scripts/java-format
else
    echo "==> Running gradlew formatJava"
    ./scripts/gradle formatJava
fi
