#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

gradle_args=()

if [ "${CI:-}" != "true" ] && [ "${OPENAI_JAVA_GRADLE_LOCAL:-true}" != "false" ]; then
  gradle_args+=(--daemon)
fi

./gradlew "${gradle_args[@]}" "$@"
