// File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

package com.openai.models.live

import com.fasterxml.jackson.annotation.JsonAnyGetter
import com.fasterxml.jackson.annotation.JsonAnySetter
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.annotation.JsonProperty
import com.openai.core.ExcludeMissing
import com.openai.core.JsonField
import com.openai.core.JsonMissing
import com.openai.core.JsonValue
import com.openai.core.checkRequired
import com.openai.errors.OpenAIInvalidDataException
import java.util.Collections
import java.util.Objects
import java.util.Optional

/**
 * An audio chunk generated by the Live model. Decode and play primary WebSocket chunks in delivery
 * order using the configured session audio format. Sideband connections receive reflected output
 * audio with timestamps.
 */
class OutputAudioDeltaEvent
@JsonCreator(mode = JsonCreator.Mode.DISABLED)
private constructor(
    private val delta: JsonField<String>,
    private val type: JsonValue,
    private val endMs: JsonField<Long>,
    private val startMs: JsonField<Long>,
    private val additionalProperties: MutableMap<String, JsonValue>,
) {

    @JsonCreator
    private constructor(
        @JsonProperty("delta") @ExcludeMissing delta: JsonField<String> = JsonMissing.of(),
        @JsonProperty("type") @ExcludeMissing type: JsonValue = JsonMissing.of(),
        @JsonProperty("end_ms") @ExcludeMissing endMs: JsonField<Long> = JsonMissing.of(),
        @JsonProperty("start_ms") @ExcludeMissing startMs: JsonField<Long> = JsonMissing.of(),
    ) : this(delta, type, endMs, startMs, mutableMapOf())

    /**
     * Base64-encoded raw audio. Primary WebSocket events use the session's configured format;
     * reflected sideband events use mono PCM16LE at 24 kHz.
     *
     * @throws OpenAIInvalidDataException if the JSON field has an unexpected type or is
     *   unexpectedly missing or null (e.g. if the server responded with an unexpected value).
     */
    fun delta(): String = delta.getRequired("delta")

    /**
     * The event type, always `session.output_audio.delta`.
     *
     * Expected to always return the following:
     * ```java
     * JsonValue.from("session.output_audio.delta")
     * ```
     *
     * However, this method can be useful for debugging and logging (e.g. if the server responded
     * with an unexpected value).
     */
    @JsonProperty("type") @ExcludeMissing fun _type(): JsonValue = type

    /**
     * Exclusive session-relative end in milliseconds. Required on reflected sideband events;
     * omitted on the primary WebSocket. Dropped output frames leave gaps between reflected ranges.
     *
     * @throws OpenAIInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun endMs(): Optional<Long> = endMs.getOptional("end_ms")

    /**
     * Inclusive session-relative start in milliseconds. Required on reflected sideband events;
     * omitted on the primary WebSocket.
     *
     * @throws OpenAIInvalidDataException if the JSON field has an unexpected type (e.g. if the
     *   server responded with an unexpected value).
     */
    fun startMs(): Optional<Long> = startMs.getOptional("start_ms")

    /**
     * Returns the raw JSON value of [delta].
     *
     * Unlike [delta], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("delta") @ExcludeMissing fun _delta(): JsonField<String> = delta

    /**
     * Returns the raw JSON value of [endMs].
     *
     * Unlike [endMs], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("end_ms") @ExcludeMissing fun _endMs(): JsonField<Long> = endMs

    /**
     * Returns the raw JSON value of [startMs].
     *
     * Unlike [startMs], this method doesn't throw if the JSON field has an unexpected type.
     */
    @JsonProperty("start_ms") @ExcludeMissing fun _startMs(): JsonField<Long> = startMs

    @JsonAnySetter
    private fun putAdditionalProperty(key: String, value: JsonValue) {
        additionalProperties.put(key, value)
    }

    @JsonAnyGetter
    @ExcludeMissing
    fun _additionalProperties(): Map<String, JsonValue> =
        Collections.unmodifiableMap(additionalProperties)

    fun toBuilder() = Builder().from(this)

    companion object {

        /**
         * Returns a mutable builder for constructing an instance of [OutputAudioDeltaEvent].
         *
         * The following fields are required:
         * ```java
         * .delta()
         * ```
         */
        @JvmStatic fun builder() = Builder()
    }

    /** A builder for [OutputAudioDeltaEvent]. */
    class Builder internal constructor() {

        private var delta: JsonField<String>? = null
        private var type: JsonValue = JsonValue.from("session.output_audio.delta")
        private var endMs: JsonField<Long> = JsonMissing.of()
        private var startMs: JsonField<Long> = JsonMissing.of()
        private var additionalProperties: MutableMap<String, JsonValue> = mutableMapOf()

        @JvmSynthetic
        internal fun from(outputAudioDeltaEvent: OutputAudioDeltaEvent) = apply {
            delta = outputAudioDeltaEvent.delta
            type = outputAudioDeltaEvent.type
            endMs = outputAudioDeltaEvent.endMs
            startMs = outputAudioDeltaEvent.startMs
            additionalProperties = outputAudioDeltaEvent.additionalProperties.toMutableMap()
        }

        /**
         * Base64-encoded raw audio. Primary WebSocket events use the session's configured format;
         * reflected sideband events use mono PCM16LE at 24 kHz.
         */
        fun delta(delta: String) = delta(JsonField.of(delta))

        /**
         * Sets [Builder.delta] to an arbitrary JSON value.
         *
         * You should usually call [Builder.delta] with a well-typed [String] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun delta(delta: JsonField<String>) = apply { this.delta = delta }

        /**
         * Sets the field to an arbitrary JSON value.
         *
         * It is usually unnecessary to call this method because the field defaults to the
         * following:
         * ```java
         * JsonValue.from("session.output_audio.delta")
         * ```
         *
         * This method is primarily for setting the field to an undocumented or not yet supported
         * value.
         */
        fun type(type: JsonValue) = apply { this.type = type }

        /**
         * Exclusive session-relative end in milliseconds. Required on reflected sideband events;
         * omitted on the primary WebSocket. Dropped output frames leave gaps between reflected
         * ranges.
         */
        fun endMs(endMs: Long) = endMs(JsonField.of(endMs))

        /**
         * Sets [Builder.endMs] to an arbitrary JSON value.
         *
         * You should usually call [Builder.endMs] with a well-typed [Long] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun endMs(endMs: JsonField<Long>) = apply { this.endMs = endMs }

        /**
         * Inclusive session-relative start in milliseconds. Required on reflected sideband events;
         * omitted on the primary WebSocket.
         */
        fun startMs(startMs: Long) = startMs(JsonField.of(startMs))

        /**
         * Sets [Builder.startMs] to an arbitrary JSON value.
         *
         * You should usually call [Builder.startMs] with a well-typed [Long] value instead. This
         * method is primarily for setting the field to an undocumented or not yet supported value.
         */
        fun startMs(startMs: JsonField<Long>) = apply { this.startMs = startMs }

        fun additionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.clear()
            putAllAdditionalProperties(additionalProperties)
        }

        fun putAdditionalProperty(key: String, value: JsonValue) = apply {
            additionalProperties.put(key, value)
        }

        fun putAllAdditionalProperties(additionalProperties: Map<String, JsonValue>) = apply {
            this.additionalProperties.putAll(additionalProperties)
        }

        fun removeAdditionalProperty(key: String) = apply { additionalProperties.remove(key) }

        fun removeAllAdditionalProperties(keys: Set<String>) = apply {
            keys.forEach(::removeAdditionalProperty)
        }

        /**
         * Returns an immutable instance of [OutputAudioDeltaEvent].
         *
         * Further updates to this [Builder] will not mutate the returned instance.
         *
         * The following fields are required:
         * ```java
         * .delta()
         * ```
         *
         * @throws IllegalStateException if any required field is unset.
         */
        fun build(): OutputAudioDeltaEvent =
            OutputAudioDeltaEvent(
                checkRequired("delta", delta),
                type,
                endMs,
                startMs,
                additionalProperties.toMutableMap(),
            )
    }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws OpenAIInvalidDataException if any value type in this object doesn't match its
     *   expected type.
     */
    fun validate(): OutputAudioDeltaEvent = apply {
        if (validated) {
            return@apply
        }

        delta()
        _type().let {
            if (it != JsonValue.from("session.output_audio.delta")) {
                throw OpenAIInvalidDataException("'type' is invalid, received $it")
            }
        }
        endMs()
        startMs()
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: OpenAIInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    @JvmSynthetic
    internal fun validity(): Int =
        (if (delta.asKnown().isPresent) 1 else 0) +
            type.let { if (it == JsonValue.from("session.output_audio.delta")) 1 else 0 } +
            (if (endMs.asKnown().isPresent) 1 else 0) +
            (if (startMs.asKnown().isPresent) 1 else 0)

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is OutputAudioDeltaEvent &&
            delta == other.delta &&
            type == other.type &&
            endMs == other.endMs &&
            startMs == other.startMs &&
            additionalProperties == other.additionalProperties
    }

    private val hashCode: Int by lazy {
        Objects.hash(delta, type, endMs, startMs, additionalProperties)
    }

    override fun hashCode(): Int = hashCode

    override fun toString() =
        "OutputAudioDeltaEvent{delta=$delta, type=$type, endMs=$endMs, startMs=$startMs, additionalProperties=$additionalProperties}"
}
