// File generated from our OpenAPI spec by Stainless.

package com.openai.models.beta.responses

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.openai.core.JsonValue
import com.openai.core.jsonMapper
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class BetaResponseQueuedEventTest {

    @Test
    fun create() {
        val betaResponseQueuedEvent =
            BetaResponseQueuedEvent.builder()
                .response(
                    BetaResponse.builder()
                        .id("id")
                        .createdAt(0.0)
                        .error(
                            BetaResponseError.builder()
                                .code(BetaResponseError.Code.SERVER_ERROR)
                                .message("message")
                                .build()
                        )
                        .incompleteDetails(
                            BetaResponse.IncompleteDetails.builder()
                                .reason(BetaResponse.IncompleteDetails.Reason.MAX_OUTPUT_TOKENS)
                                .build()
                        )
                        .instructions("string")
                        .metadata(
                            BetaResponse.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .model(BetaResponse.Model.GPT_5_1)
                        .addOutput(
                            BetaResponseOutputMessage.builder()
                                .id("id")
                                .addContent(
                                    BetaResponseOutputText.builder()
                                        .addAnnotation(
                                            BetaResponseOutputText.Annotation.FileCitation.builder()
                                                .fileId("file_id")
                                                .filename("filename")
                                                .index(0L)
                                                .build()
                                        )
                                        .text("text")
                                        .addLogprob(
                                            BetaResponseOutputText.Logprob.builder()
                                                .token("token")
                                                .addByte(0L)
                                                .logprob(0.0)
                                                .addTopLogprob(
                                                    BetaResponseOutputText.Logprob.TopLogprob
                                                        .builder()
                                                        .token("token")
                                                        .addByte(0L)
                                                        .logprob(0.0)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .status(BetaResponseOutputMessage.Status.IN_PROGRESS)
                                .agent(
                                    BetaResponseOutputMessage.Agent.builder()
                                        .agentName("agent_name")
                                        .build()
                                )
                                .phase(BetaResponseOutputMessage.Phase.COMMENTARY)
                                .build()
                        )
                        .parallelToolCalls(true)
                        .temperature(1.0)
                        .toolChoice(BetaToolChoiceOptions.NONE)
                        .addTool(
                            BetaFunctionTool.builder()
                                .name("name")
                                .parameters(
                                    BetaFunctionTool.Parameters.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .strict(true)
                                .addAllowedCaller(BetaFunctionTool.AllowedCaller.DIRECT)
                                .deferLoading(true)
                                .description("description")
                                .outputSchema(
                                    BetaFunctionTool.OutputSchema.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .build()
                        )
                        .topP(1.0)
                        .background(true)
                        .completedAt(0.0)
                        .conversation(BetaResponse.Conversation.builder().id("id").build())
                        .maxOutputTokens(0L)
                        .maxToolCalls(0L)
                        .moderation(
                            BetaResponse.Moderation.builder()
                                .input(
                                    BetaResponse.Moderation.Input.ModerationResult.builder()
                                        .categories(
                                            BetaResponse.Moderation.Input.ModerationResult
                                                .Categories
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from(true))
                                                .build()
                                        )
                                        .categoryAppliedInputTypes(
                                            BetaResponse.Moderation.Input.ModerationResult
                                                .CategoryAppliedInputTypes
                                                .builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from(listOf("text")),
                                                )
                                                .build()
                                        )
                                        .categoryScores(
                                            BetaResponse.Moderation.Input.ModerationResult
                                                .CategoryScores
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from(0))
                                                .build()
                                        )
                                        .flagged(true)
                                        .model("model")
                                        .build()
                                )
                                .output(
                                    BetaResponse.Moderation.Output.ModerationResult.builder()
                                        .categories(
                                            BetaResponse.Moderation.Output.ModerationResult
                                                .Categories
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from(true))
                                                .build()
                                        )
                                        .categoryAppliedInputTypes(
                                            BetaResponse.Moderation.Output.ModerationResult
                                                .CategoryAppliedInputTypes
                                                .builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from(listOf("text")),
                                                )
                                                .build()
                                        )
                                        .categoryScores(
                                            BetaResponse.Moderation.Output.ModerationResult
                                                .CategoryScores
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from(0))
                                                .build()
                                        )
                                        .flagged(true)
                                        .model("model")
                                        .build()
                                )
                                .build()
                        )
                        .previousResponseId("previous_response_id")
                        .prompt(
                            BetaResponsePrompt.builder()
                                .id("id")
                                .variables(
                                    BetaResponsePrompt.Variables.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .version("version")
                                .build()
                        )
                        .promptCacheKey("prompt-cache-key-1234")
                        .promptCacheOptions(
                            BetaResponse.PromptCacheOptions.builder()
                                .mode(BetaResponse.PromptCacheOptions.Mode.IMPLICIT)
                                .ttl(BetaResponse.PromptCacheOptions.Ttl._30M)
                                .build()
                        )
                        .promptCacheRetention(BetaResponse.PromptCacheRetention.IN_MEMORY)
                        .reasoning(
                            BetaResponse.Reasoning.builder()
                                .context(BetaResponse.Reasoning.Context.AUTO)
                                .effort(BetaResponse.Reasoning.Effort.NONE)
                                .generateSummary(BetaResponse.Reasoning.GenerateSummary.AUTO)
                                .mode(BetaResponse.Reasoning.Mode.STANDARD)
                                .summary(BetaResponse.Reasoning.Summary.AUTO)
                                .build()
                        )
                        .safetyIdentifier("safety-identifier-1234")
                        .serviceTier(BetaResponse.ServiceTier.AUTO)
                        .status(BetaResponseStatus.COMPLETED)
                        .text(
                            BetaResponseTextConfig.builder()
                                .formatText()
                                .verbosity(BetaResponseTextConfig.Verbosity.LOW)
                                .build()
                        )
                        .topLogprobs(0L)
                        .truncation(BetaResponse.Truncation.AUTO)
                        .usage(
                            BetaResponseUsage.builder()
                                .inputTokens(0L)
                                .inputTokensDetails(
                                    BetaResponseUsage.InputTokensDetails.builder()
                                        .cacheWriteTokens(0L)
                                        .cachedTokens(0L)
                                        .build()
                                )
                                .outputTokens(0L)
                                .outputTokensDetails(
                                    BetaResponseUsage.OutputTokensDetails.builder()
                                        .reasoningTokens(0L)
                                        .build()
                                )
                                .totalTokens(0L)
                                .build()
                        )
                        .user("user-1234")
                        .build()
                )
                .sequenceNumber(0L)
                .agent(BetaResponseQueuedEvent.Agent.builder().agentName("agent_name").build())
                .build()

        assertThat(betaResponseQueuedEvent.response())
            .isEqualTo(
                BetaResponse.builder()
                    .id("id")
                    .createdAt(0.0)
                    .error(
                        BetaResponseError.builder()
                            .code(BetaResponseError.Code.SERVER_ERROR)
                            .message("message")
                            .build()
                    )
                    .incompleteDetails(
                        BetaResponse.IncompleteDetails.builder()
                            .reason(BetaResponse.IncompleteDetails.Reason.MAX_OUTPUT_TOKENS)
                            .build()
                    )
                    .instructions("string")
                    .metadata(
                        BetaResponse.Metadata.builder()
                            .putAdditionalProperty("foo", JsonValue.from("string"))
                            .build()
                    )
                    .model(BetaResponse.Model.GPT_5_1)
                    .addOutput(
                        BetaResponseOutputMessage.builder()
                            .id("id")
                            .addContent(
                                BetaResponseOutputText.builder()
                                    .addAnnotation(
                                        BetaResponseOutputText.Annotation.FileCitation.builder()
                                            .fileId("file_id")
                                            .filename("filename")
                                            .index(0L)
                                            .build()
                                    )
                                    .text("text")
                                    .addLogprob(
                                        BetaResponseOutputText.Logprob.builder()
                                            .token("token")
                                            .addByte(0L)
                                            .logprob(0.0)
                                            .addTopLogprob(
                                                BetaResponseOutputText.Logprob.TopLogprob.builder()
                                                    .token("token")
                                                    .addByte(0L)
                                                    .logprob(0.0)
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .build()
                            )
                            .status(BetaResponseOutputMessage.Status.IN_PROGRESS)
                            .agent(
                                BetaResponseOutputMessage.Agent.builder()
                                    .agentName("agent_name")
                                    .build()
                            )
                            .phase(BetaResponseOutputMessage.Phase.COMMENTARY)
                            .build()
                    )
                    .parallelToolCalls(true)
                    .temperature(1.0)
                    .toolChoice(BetaToolChoiceOptions.NONE)
                    .addTool(
                        BetaFunctionTool.builder()
                            .name("name")
                            .parameters(
                                BetaFunctionTool.Parameters.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .strict(true)
                            .addAllowedCaller(BetaFunctionTool.AllowedCaller.DIRECT)
                            .deferLoading(true)
                            .description("description")
                            .outputSchema(
                                BetaFunctionTool.OutputSchema.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("bar"))
                                    .build()
                            )
                            .build()
                    )
                    .topP(1.0)
                    .background(true)
                    .completedAt(0.0)
                    .conversation(BetaResponse.Conversation.builder().id("id").build())
                    .maxOutputTokens(0L)
                    .maxToolCalls(0L)
                    .moderation(
                        BetaResponse.Moderation.builder()
                            .input(
                                BetaResponse.Moderation.Input.ModerationResult.builder()
                                    .categories(
                                        BetaResponse.Moderation.Input.ModerationResult.Categories
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from(true))
                                            .build()
                                    )
                                    .categoryAppliedInputTypes(
                                        BetaResponse.Moderation.Input.ModerationResult
                                            .CategoryAppliedInputTypes
                                            .builder()
                                            .putAdditionalProperty(
                                                "foo",
                                                JsonValue.from(listOf("text")),
                                            )
                                            .build()
                                    )
                                    .categoryScores(
                                        BetaResponse.Moderation.Input.ModerationResult
                                            .CategoryScores
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from(0))
                                            .build()
                                    )
                                    .flagged(true)
                                    .model("model")
                                    .build()
                            )
                            .output(
                                BetaResponse.Moderation.Output.ModerationResult.builder()
                                    .categories(
                                        BetaResponse.Moderation.Output.ModerationResult.Categories
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from(true))
                                            .build()
                                    )
                                    .categoryAppliedInputTypes(
                                        BetaResponse.Moderation.Output.ModerationResult
                                            .CategoryAppliedInputTypes
                                            .builder()
                                            .putAdditionalProperty(
                                                "foo",
                                                JsonValue.from(listOf("text")),
                                            )
                                            .build()
                                    )
                                    .categoryScores(
                                        BetaResponse.Moderation.Output.ModerationResult
                                            .CategoryScores
                                            .builder()
                                            .putAdditionalProperty("foo", JsonValue.from(0))
                                            .build()
                                    )
                                    .flagged(true)
                                    .model("model")
                                    .build()
                            )
                            .build()
                    )
                    .previousResponseId("previous_response_id")
                    .prompt(
                        BetaResponsePrompt.builder()
                            .id("id")
                            .variables(
                                BetaResponsePrompt.Variables.builder()
                                    .putAdditionalProperty("foo", JsonValue.from("string"))
                                    .build()
                            )
                            .version("version")
                            .build()
                    )
                    .promptCacheKey("prompt-cache-key-1234")
                    .promptCacheOptions(
                        BetaResponse.PromptCacheOptions.builder()
                            .mode(BetaResponse.PromptCacheOptions.Mode.IMPLICIT)
                            .ttl(BetaResponse.PromptCacheOptions.Ttl._30M)
                            .build()
                    )
                    .promptCacheRetention(BetaResponse.PromptCacheRetention.IN_MEMORY)
                    .reasoning(
                        BetaResponse.Reasoning.builder()
                            .context(BetaResponse.Reasoning.Context.AUTO)
                            .effort(BetaResponse.Reasoning.Effort.NONE)
                            .generateSummary(BetaResponse.Reasoning.GenerateSummary.AUTO)
                            .mode(BetaResponse.Reasoning.Mode.STANDARD)
                            .summary(BetaResponse.Reasoning.Summary.AUTO)
                            .build()
                    )
                    .safetyIdentifier("safety-identifier-1234")
                    .serviceTier(BetaResponse.ServiceTier.AUTO)
                    .status(BetaResponseStatus.COMPLETED)
                    .text(
                        BetaResponseTextConfig.builder()
                            .formatText()
                            .verbosity(BetaResponseTextConfig.Verbosity.LOW)
                            .build()
                    )
                    .topLogprobs(0L)
                    .truncation(BetaResponse.Truncation.AUTO)
                    .usage(
                        BetaResponseUsage.builder()
                            .inputTokens(0L)
                            .inputTokensDetails(
                                BetaResponseUsage.InputTokensDetails.builder()
                                    .cacheWriteTokens(0L)
                                    .cachedTokens(0L)
                                    .build()
                            )
                            .outputTokens(0L)
                            .outputTokensDetails(
                                BetaResponseUsage.OutputTokensDetails.builder()
                                    .reasoningTokens(0L)
                                    .build()
                            )
                            .totalTokens(0L)
                            .build()
                    )
                    .user("user-1234")
                    .build()
            )
        assertThat(betaResponseQueuedEvent.sequenceNumber()).isEqualTo(0L)
        assertThat(betaResponseQueuedEvent.agent())
            .contains(BetaResponseQueuedEvent.Agent.builder().agentName("agent_name").build())
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val betaResponseQueuedEvent =
            BetaResponseQueuedEvent.builder()
                .response(
                    BetaResponse.builder()
                        .id("id")
                        .createdAt(0.0)
                        .error(
                            BetaResponseError.builder()
                                .code(BetaResponseError.Code.SERVER_ERROR)
                                .message("message")
                                .build()
                        )
                        .incompleteDetails(
                            BetaResponse.IncompleteDetails.builder()
                                .reason(BetaResponse.IncompleteDetails.Reason.MAX_OUTPUT_TOKENS)
                                .build()
                        )
                        .instructions("string")
                        .metadata(
                            BetaResponse.Metadata.builder()
                                .putAdditionalProperty("foo", JsonValue.from("string"))
                                .build()
                        )
                        .model(BetaResponse.Model.GPT_5_1)
                        .addOutput(
                            BetaResponseOutputMessage.builder()
                                .id("id")
                                .addContent(
                                    BetaResponseOutputText.builder()
                                        .addAnnotation(
                                            BetaResponseOutputText.Annotation.FileCitation.builder()
                                                .fileId("file_id")
                                                .filename("filename")
                                                .index(0L)
                                                .build()
                                        )
                                        .text("text")
                                        .addLogprob(
                                            BetaResponseOutputText.Logprob.builder()
                                                .token("token")
                                                .addByte(0L)
                                                .logprob(0.0)
                                                .addTopLogprob(
                                                    BetaResponseOutputText.Logprob.TopLogprob
                                                        .builder()
                                                        .token("token")
                                                        .addByte(0L)
                                                        .logprob(0.0)
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .build()
                                )
                                .status(BetaResponseOutputMessage.Status.IN_PROGRESS)
                                .agent(
                                    BetaResponseOutputMessage.Agent.builder()
                                        .agentName("agent_name")
                                        .build()
                                )
                                .phase(BetaResponseOutputMessage.Phase.COMMENTARY)
                                .build()
                        )
                        .parallelToolCalls(true)
                        .temperature(1.0)
                        .toolChoice(BetaToolChoiceOptions.NONE)
                        .addTool(
                            BetaFunctionTool.builder()
                                .name("name")
                                .parameters(
                                    BetaFunctionTool.Parameters.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .strict(true)
                                .addAllowedCaller(BetaFunctionTool.AllowedCaller.DIRECT)
                                .deferLoading(true)
                                .description("description")
                                .outputSchema(
                                    BetaFunctionTool.OutputSchema.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("bar"))
                                        .build()
                                )
                                .build()
                        )
                        .topP(1.0)
                        .background(true)
                        .completedAt(0.0)
                        .conversation(BetaResponse.Conversation.builder().id("id").build())
                        .maxOutputTokens(0L)
                        .maxToolCalls(0L)
                        .moderation(
                            BetaResponse.Moderation.builder()
                                .input(
                                    BetaResponse.Moderation.Input.ModerationResult.builder()
                                        .categories(
                                            BetaResponse.Moderation.Input.ModerationResult
                                                .Categories
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from(true))
                                                .build()
                                        )
                                        .categoryAppliedInputTypes(
                                            BetaResponse.Moderation.Input.ModerationResult
                                                .CategoryAppliedInputTypes
                                                .builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from(listOf("text")),
                                                )
                                                .build()
                                        )
                                        .categoryScores(
                                            BetaResponse.Moderation.Input.ModerationResult
                                                .CategoryScores
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from(0))
                                                .build()
                                        )
                                        .flagged(true)
                                        .model("model")
                                        .build()
                                )
                                .output(
                                    BetaResponse.Moderation.Output.ModerationResult.builder()
                                        .categories(
                                            BetaResponse.Moderation.Output.ModerationResult
                                                .Categories
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from(true))
                                                .build()
                                        )
                                        .categoryAppliedInputTypes(
                                            BetaResponse.Moderation.Output.ModerationResult
                                                .CategoryAppliedInputTypes
                                                .builder()
                                                .putAdditionalProperty(
                                                    "foo",
                                                    JsonValue.from(listOf("text")),
                                                )
                                                .build()
                                        )
                                        .categoryScores(
                                            BetaResponse.Moderation.Output.ModerationResult
                                                .CategoryScores
                                                .builder()
                                                .putAdditionalProperty("foo", JsonValue.from(0))
                                                .build()
                                        )
                                        .flagged(true)
                                        .model("model")
                                        .build()
                                )
                                .build()
                        )
                        .previousResponseId("previous_response_id")
                        .prompt(
                            BetaResponsePrompt.builder()
                                .id("id")
                                .variables(
                                    BetaResponsePrompt.Variables.builder()
                                        .putAdditionalProperty("foo", JsonValue.from("string"))
                                        .build()
                                )
                                .version("version")
                                .build()
                        )
                        .promptCacheKey("prompt-cache-key-1234")
                        .promptCacheOptions(
                            BetaResponse.PromptCacheOptions.builder()
                                .mode(BetaResponse.PromptCacheOptions.Mode.IMPLICIT)
                                .ttl(BetaResponse.PromptCacheOptions.Ttl._30M)
                                .build()
                        )
                        .promptCacheRetention(BetaResponse.PromptCacheRetention.IN_MEMORY)
                        .reasoning(
                            BetaResponse.Reasoning.builder()
                                .context(BetaResponse.Reasoning.Context.AUTO)
                                .effort(BetaResponse.Reasoning.Effort.NONE)
                                .generateSummary(BetaResponse.Reasoning.GenerateSummary.AUTO)
                                .mode(BetaResponse.Reasoning.Mode.STANDARD)
                                .summary(BetaResponse.Reasoning.Summary.AUTO)
                                .build()
                        )
                        .safetyIdentifier("safety-identifier-1234")
                        .serviceTier(BetaResponse.ServiceTier.AUTO)
                        .status(BetaResponseStatus.COMPLETED)
                        .text(
                            BetaResponseTextConfig.builder()
                                .formatText()
                                .verbosity(BetaResponseTextConfig.Verbosity.LOW)
                                .build()
                        )
                        .topLogprobs(0L)
                        .truncation(BetaResponse.Truncation.AUTO)
                        .usage(
                            BetaResponseUsage.builder()
                                .inputTokens(0L)
                                .inputTokensDetails(
                                    BetaResponseUsage.InputTokensDetails.builder()
                                        .cacheWriteTokens(0L)
                                        .cachedTokens(0L)
                                        .build()
                                )
                                .outputTokens(0L)
                                .outputTokensDetails(
                                    BetaResponseUsage.OutputTokensDetails.builder()
                                        .reasoningTokens(0L)
                                        .build()
                                )
                                .totalTokens(0L)
                                .build()
                        )
                        .user("user-1234")
                        .build()
                )
                .sequenceNumber(0L)
                .agent(BetaResponseQueuedEvent.Agent.builder().agentName("agent_name").build())
                .build()

        val roundtrippedBetaResponseQueuedEvent =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(betaResponseQueuedEvent),
                jacksonTypeRef<BetaResponseQueuedEvent>(),
            )

        assertThat(roundtrippedBetaResponseQueuedEvent).isEqualTo(betaResponseQueuedEvent)
    }
}
